A_distance = float(input("A distance covered = "))
A_beats_B = float(input(" A beats by B distance = "))
B_distance = (A_distance - A_beats_B)
print(f'B covered distance ={B_distance}')
first_race_time_difference = float(input("first race time difference ="))
other_time_difference = float(input("another race time difference ="))
time_taken_by_A = (first_race_time_difference*A_distance - B_distance*other_time_difference)/(B_distance - A_distance)
print(f'time taken by A = {first_race_time_difference}*{A_distance}-{B_distance}*{other_time_difference}/{B_distance}-{A_distance}')
print(f'time taken by A = {time_taken_by_A} sec')
time_taken_by_B = (time_taken_by_A + first_race_time_difference)
print(f'time taken by B = {time_taken_by_A}+{first_race_time_difference}')
print(f'time taken by B = {time_taken_by_B} sec')
speed_of_A = (A_distance/time_taken_by_A)
print(f'speed of A = {A_distance}/{time_taken_by_A}')
speed_of_B = (B_distance/time_taken_by_B)
print(f'speed of A = {B_distance}/{time_taken_by_A}')
print(f'speed of A =  {round(speed_of_A,2)} m/sec')
print(f'speed of B = {round(speed_of_B,2)} m/sec')
